### ISSUE TITLE
Doesn't work without secrets volume

### ISSUE THREAD

**Issue by Janpot** [codeablehq/KubePress#2]
I prefer to include my secrets by using

```yaml
envFrom:
- secretRef:
    name: my-secret
```

So that I don't need to pass them with the volume. But it seems like the container doesn't work when there's no volume attached. It keeps giving errors of

```sh
cat: /etc/secrets/*: No such file or directory
```
